env: "local"
storages:
  server: ""
  user: ""
  port: 1433
  password: ""
  numberOfSparePhrases: 5

http_server:
  adress: "localhost"
  port: 8080
  read_timeout: 4s
  idle_timeout: 60s
keys:
  path: ""
logger: 
  path: "./log/"
  type: ".log"
  level: "DEBUG"